### ISSUE TITLE
rcon sends 2 arguments

### ISSUE THREAD

**Issue by hbokh** [fjerlv/deathquake#2]
FYI I had to strip "utf-8" from https://github.com/fjerlv/deathquake/blob/master/stats/management/commands/gamemaster.py#L101 since I had this error at startup of the gamemaster:

```
  File "/srv/deathquake/stats/management/commands/gamemaster.py", line 101, in send_rcon
    self.sock.sendall(PACKAGE_PREFIX + bytes(RCON_PREFIX + command + '\n', 'utf-8'))
TypeError: str() takes at most 1 argument (2 given)
```

Anyway, _mange tak_ for such a fun tool! 👍

**Comment by fjerlv** [comment]
Hi @hbokh 

Thanks for the issue!

Unfortunately I have been spare time coding on this project for a while without pushing to GitHub. I'm going to release a new version soon, docker compatible, which should fix this issue :-)

Best Regards,
Frederik
